# These variables define the project; they may not need to be changed
project:
  type: book
  output-dir: _book

# These variables define the book contents - adjust them as necessary
book:
  # [A] BOOK TITLE
  title: "MP968: Experimental Design Workshop"
  reader-mode: true
  
  # The cover image and favicon; these may not need to be changed
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  
  # Sets the page footer text/images
  # [B] FOOTER TEXT
  page-footer:
    left: |
      This workshop is written and maintained by Dr Leighton Pritchard
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  # Sets the URL for the repository
  # [C] GITHUB REPOSITORY URL
  repo-url: https://github.com/sipbs-compbiol/MP968-Workshop_Experimental_Design
  repo-branch: main
  repo-actions: [edit, issue]

  # Sets author information and publication/presentation date
  # [D] AUTHOR INFORMATION AND PUBLICATION/PRESENTATION DATE
  author: "Leighton Pritchard"
  date: "25/11/2024"

  # Define chapters and sections here
  # [E] CHAPTERS AND SECTIONS
  chapters:
    - index.qmd
    
    - part: intro.qmd
      chapters:
        - disclaimer.qmd
        - objectives.qmd

    - part: why_design.qmd
      chapters:
        - unnecessary_suffering.qmd
        - design_minimises_suffering.qmd
        - reporting.qmd

    - part: experimental_design.qmd
      chapters: 
        - decide_variables.qmd
        - decide_treatments.qmd

    - part: power.qmd
      chapters: 
        - sim_sample_size.qmd
        - sampling.qmd
        - power_considerations.qmd
        - underpowered.qmd
        - effect_sizes.qmd
        - g_power.qmd
    
    - part: nc3rs-eda.qmd
      chapters: 
        - eda_account.qmd
        - workshop_experiment.qmd
        - create_new_diagram.qmd
        - add_experiment_node.qmd
        - group_assignment.qmd
        - interventions.qmd
        - critique1.qmd
        - both_sexes.qmd
        - analysis_suggestion.qmd
        - sample_size.qmd
        - communicate.qmd
        - templates.qmd
  
    - part: cause_and_effect.qmd
      chapters:
        - problem.qmd
        - causal_models.qmd
        # - dags.qmd

    - part: measurement.qmd
      chapters: 
        - wet_earth.qmd
        - globe_model.qmd
        - globe_analysis.qmd
        - dodecahedron.qmd
        - observations.qmd

    - summary.qmd
    - references.qmd
    - further_reading.qmd

# Location of BibTeX format reference file; may not need to be changed
bibliography: references.bib

# Formatting and theme; may not need to be changed
format:
  html:
    theme: cosmo
    
    code-link: true
    code-fold: true
    code-summary: "Show the code"

    author-meta: "Leighton Pritchard"
  
#  pdf:
#    documentclass: scrreprt

# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto

# Add custom callouts
custom-callout:
  callout-case-study:
    title: "Case Study"
    icon-symbol: "🔍"
    color: "#FFA500"
  callout-data:
    icon-symbol: "📊"
    title: "Data Analysis"
    color: "#32CD32"
  callout-discussion:
    title: "Discussion Questions:"
    icon-symbol: "✨"
    color: "#BA55D3"
  callout-microbe:
    title: "Microbe Profile"
    icon-symbol: "🧫"
    color: "#1E90FF"
  callout-thumbs-up:
    title: "Great job!"
    icon-symbol: "👍"
    color: "#008000"
  callout-todo:
    icon-symbol: "📝"
    color: "pink"
  callout-challenge:
    title: "Challenge"
    icon-symbol: "🧑‍🏫"
    color: "aquamarine"
  callout-question:
    title: "Question"
    icon-symbol: "🙋"
    color: "yellow"
  callout-questions:
    title: "Questions"
    icon-symbol: "🙋️"
    color: "yellow"  

filters:
  - custom-callout
  - naquiz
