# These variables define the project; they may not need to be changed
project:
  type: book
  output-dir: _book

# These variables define the book contents - adjust them as necessary
book:
  # [A] BOOK TITLE
  title: "MP968: Experimental Design Workshop"
  reader-mode: true
  
  # The cover image and favicon; these may not need to be changed
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  
  # Sets the page footer text/images
  # [B] FOOTER TEXT
  page-footer:
    left: |
      This workshop is written and maintained by Dr Leighton Pritchard
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  # Sets the URL for the repository
  # [C] GITHUB REPOSITORY URL
  repo-url: https://github.com/sipbs-compbiol/MP968-Workshop_Experimental_Design
  repo-branch: main
  repo-actions: [edit, issue]

  # Sets author information and publication/presentation date
  # [D] AUTHOR INFORMATION AND PUBLICATION/PRESENTATION DATE
  author: "Leighton Pritchard"
  date: "25/11/2024"

  # Define chapters and sections here
  # [E] CHAPTERS AND SECTIONS
  chapters:
    - index.qmd
    - intro.qmd

    - part: cause_and_effect.qmd
      chapters:
        - problem.qmd
        - dags.qmd

    - part: measurement.qmd
      chapters: 
        - wet_earth.qmd
        
    - part: power.qmd
      chapters: 
        - power_considerations.qmd
        - underpowered.qmd
        - effect_sizes.qmd
        - g_power.qmd
    
    - part: nc3rs-eda.qmd
      chapters: 
        - eda_account.qmd
        - workshop_experiment.qmd
        - create_new_diagram.qmd
        - add_experiment_node.qmd
        - group_assignment.qmd
        - interventions.qmd
        - critique1.qmd
        - both_sexes.qmd
        - analysis_suggestion.qmd
        - sample_size.qmd
    
    - references.qmd
    - further_reading.qmd

# Location of BibTeX format reference file; may not need to be changed
bibliography: references.bib

# Formatting and theme; may not need to be changed
format:
  html:
    theme: cosmo
    code-link: true
    
    author-meta: "Leighton Pritchard"
  
#  pdf:
#    documentclass: scrreprt

# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto

