# Measurement {#sec-measurement}

In this section of material, we are going to think about what it means to measure some kind of value. You're all scientists and you will have measured things before, so you might think that you should be working with more advanced material - I can sympathise with that. But we're going to look at measurement in a way that emphasises the role of **scientific modelling** and explores the idea of an estimate as a _distribution of more- or less-likely possibilities_ rather than a single point value, and how sample size influences the shape and interpretation of that distribution.

::: {.callout-tip}
## Data Context

The example we are using is attempting to answer the question What proportion of the Earth's surface is covered by water?"

You probably already have an idea of what proportion that is - about 70%. But pretend that you don't already know.

Even if you _did_ already know, have you thought about…

- How accurate is that value of 70%?
- How would you go about measuring the exact surface area?
  - Aren't there tides? And coastal erosion? And other things that might affect this?

Aren't we really _estimating_ the measurement? 

And, if we're making an estimate, then don't we need to try to understand how accurate our estimate might be?
:::

Rather than develop these ideas in formal mathematical notation, this section is trying to develop some intuition about measurement, probability, and statistics.
